<a href="https://colab.research.google.com/github/dheeraj7000/Colab-NB-GenAI/blob/main/Sanskrit_Language_Model_using_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 16.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.8 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of multiprocess to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.0 MB/s eta 0:00:00


In [ ]:
from google.colab import userdata
import os
HUGGINGFACEHUB_API_TOKEN = userdata.get('HUGGINGFACEHUB_API_TOKEN')
HUGGINGFACEHUB_API_TOKEN = os.environ

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

In [ ]:
# example with OSCAR 2201
from datasets import load_dataset


dataset = load_dataset("oscar-corpus/OSCAR-2201",
                        use_auth_token=True, # required
                        language="sa",
                        streaming=True, # optional
                        split="train") # optional

for d in dataset:
    print(d)

/usr/local/lib/python3.10/dist-packages/datasets/load.py:2483: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/datasets/load.py:1429: FutureWarning: The repository for oscar-corpus/OSCAR-2201 contains custom code which must be executed to correctly load the dataset. You can inspect t

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



{'id': 854, 'text': '१०) bhAva-karma-prakriyAyAm-ciNvadbhAvaH---ajantAnAM-han-grah-dRush-ityeShAM-ca-lRDAdiShu-_2017-08-20\n११) bhAva-karma-prakriyAyAM-ciNvadbhAvaH---iDAgamasya-vidhAnam-ArdhadhAtukasyeDvalAdeH-iti-na_2017-08-27\n१२) NijantadhAtUnAmapi-lRuTAdiShu-bhAva-karma-prakriyAyAM-ciNvadbhAvaH_2017-09-10\n१३) bhAve-karmaNi-lung-lakArasya-ksa-pratyayAnta-rUpANI_2017-09-24\n१४) bhAve-karmaNi-lung-lakArasya-ksa-pratyayAnta-rUpANI---दुह्\u200c-दिह्\u200c-लिह्\u200c-गुह्\u200c_2017-10-01\nभावार्थे कर्मण्यर्थे च यः प्रत्ययः धातुभ्यः विधीयते, सः आर्धधातुकसंज्ञकः इति कारणतः इष्टरूपाणां साधनार्थम्\u200c आर्धधातुकप्रक्रिया उपयुज्यते | आर्धधातुकप्रक्रिया इत्यस्मात्\u200c धातुगणचिन्तनं न भवति | सर्वे उपद्विसहस्रं धातवः अन्तिमवर्णम् अधिकृत्य श्रेणीक्रियन्ते | यक्\u200c-प्रत्ययश्च वलादिः नास्ति इत्यस्मात्\u200c इडागमः न भवति कुत्रापि |\nयः तिङ्\u200c अथवा कृत्\u200c-प्रत्ययः धातोः परो वर्तते स च भाववाची कर्मवाची वा चेत्\u200c, धातोः यक्\u200c-प्रत्ययः विधीयते सार्वधातुके यक्\u200c (३.१.६७) इति

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



{'id': 4465, 'text': 'जनको ह वैदेह आसाञ्चक्रे । अस्य सम्बन्धः — शारीराद्यानष्टौ पुरुषान्निरुह्य, प्रत्युह्य पुनर्हृदये, दिग्भेदेन च पुनः पञ्चधा व्यूह्य, हृदये प्रत्युह्य, हृदयं शरीरं च पुनरन्योन्यप्रतिष्ठं प्राणादिपञ्चवृत्त्यात्मके समानाख्ये जगदात्मनि सूत्र उपसंहृत्य, जगदात्मानं शरीरहृदयसूत्रावस्थमतिक्रान्तवान् य औपनिषदः पुरुषः नेति नेतीति व्यपदिष्टः, स साक्षाच्च उपादानकारणस्वरूपेण च निर्दिष्टः ‘विज्ञानमानन्दम्’ इति । तस्यैव वागादिदेवताद्वारेण पुनरधिगमः कर्तव्य इति अधिगमनोपायान्तरार्थोऽयमारम्भो ब्राह्मणद्वयस्य । आख्यायिका तु आचारप्रदर्शनार्था —\nओं जनको ह वैदेह आसाञ्चक्रेऽथ ह याज्ञवल्क्य आवव्राज । तंहोवाच याज्ञवल्क्य किमर्थमचारीः पशूनिच्छन्नण्वन्तानिति । उभयमेव सम्राडिति होवाच ॥ १ ॥\nजनको ह वैदेह आसाञ्चक्रे आसनं कृतवान् आस्थायिकां दत्तवानित्यर्थः, दर्शनकामेभ्यो राज्ञः । अथ ह तस्मिन्नवसरे याज्ञवल्क्य आवव्राज आगतवान् आत्मनो योगक्षेमार्थम् , राज्ञो वा विविदिषां दृष्ट्वा अनुग्रहार्थम् । तमागतं याज्ञवल्क्यं यथावत्पूजां कृत्वा उवाच ह उक्तवान् जनकः — हे याज्ञवल्क्य किमर्थमचारीः आगतोऽसि ; किं 

In [ ]:
dataset = [x for x in dataset]
len(dataset)

4472

In [ ]:
def save_text_to_file(text_list, file_path):
    with open(file_path, 'w') as file:
        for line in text_list:
            file.write(line + '\n')

# Example text list
files = [str(x['text']) for x in dataset]

# File path where the text will be saved
file_path = "output.txt"

# Save the text list to a file
save_text_to_file(files, file_path)

print(f"Text saved to '{file_path}'")

Text saved to 'output.txt'


In [ ]:
dataset[0]['text']

'पाठः क्रियेटिव कॉमन्स ऐट्रिब्यूशन/शेयर-अलाइक अभिज्ञापत्रस्य अन्तर्गततया उपलब्धः अस्ति; अन्याः संस्थित्यः अपि सन्ति । अधिकं ज्ञातुम् अत्र उपयोगस्य संस्थितिं पश्यतु ।'

In [ ]:
from pathlib import Path

from tokenizers import ByteLevelBPETokenizer

files = ['output.txt']

In [ ]:
# Initialize a tokenizer
tokenizer = ByteLevelBPETokenizer()

In [ ]:
# Customize training
tokenizer.train(files=files, vocab_size=52_000, min_frequency=2, special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])

# Save files to disk
tokenizer.save_model(".", "sansberto")

['./sansberto-vocab.json', './sansberto-merges.txt']

In [ ]:
from tokenizers.implementations import ByteLevelBPETokenizer
from tokenizers.processors import BertProcessing


tokenizer = ByteLevelBPETokenizer(
    "sansberto-vocab.json",
    "sansberto-merges.txt",
)
tokenizer._tokenizer.post_processor = BertProcessing(
    ("</s>", tokenizer.token_to_id("</s>")),
    ("<s>", tokenizer.token_to_id("<s>")),
)
tokenizer.enable_truncation(max_length=512)

In [ ]:
# List of Sanskrit sentences
sanskrit_sentences = [
    "अहं गच्छामि।",  # Aham gacchāmi. - I am going.
    "सत्यं एव जयते।",  # Satyam eva jayate. - Truth alone triumphs.
    "अहं भवतः मित्रम् अस्मि।",  # Aham bhavataḥ mitram asmi. - I am your friend.
    "विद्याधनं सर्वधनप्रधानम्।",  # Vidyādhanam sarvadhanapradhānam. - Knowledge is the foremost wealth.
    "अहं संस्कृतभाषां पठामि।",  # Aham sanskritabhāṣām paṭhāmi. - I am studying the Sanskrit language.
    "सर्वं जगदिदं त्वत्पूर्वं विचित्रम्।",  # Sarvam jagadidam tvatpūrvam vicitram. - All this world was strange before you.
    "सुखं त्यक्त्वा दुःखमानीष्यति।",  # Sukham tyaktvā duḥkha mānīṣyati. - Having given up pleasure, one will foresee pain.
    "न विद्या सदैव युक्ता सदैव समर्पणे रता।",  # Na vidyā sadaiva yuktā sadaiva samarpaṇe ratā. - Knowledge is never associated with devotion, always involved in offerings.
    "विद्याधनं सर्वधनप्रधानम्।",  # Vidyādhanam sarvadhanapradhānam. - Knowledge is the foremost wealth.
    "आत्मनो मोक्षार्थं जगद्धिताय च।",  # Ātmano mokṣārtham jagaddhitāya ca. - For one's own liberation and for the welfare of the world.
]

# # Print each sentence
# for sentence in sanskrit_sentences:
#     print(sentence)


In [ ]:
print(
    tokenizer.encode("आत्मनो मोक्षार्थं जगद्धिताय च।")
)

Encoding(num_tokens=25, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])


In [ ]:
x = tokenizer.encode(text[:10000])

In [ ]:
print(x.tokens)

['<s>', 'प', 'ा', 'à¤ł', 'à¤ĥ', 'Ġà¤ķ', 'à¥į', 'र', 'ि', 'य', 'à¥ĩ', 'à¤Ł', 'ि', 'व', 'Ġà¤ķ', 'à¥ī', 'मन', 'à¥į', 'स', 'Ġà¤IJà¤Ł', 'à¥į', 'र', 'ि', 'ब', 'à¥į', 'य', 'à¥Ĥ', 'शन', '/', 'श', 'à¥ĩ', 'यर', '-', 'à¤ħल', 'ा', 'à¤ĩà¤ķ', 'Ġà¤ħà¤Ń', 'ि', 'à¤ľ', 'à¥į', 'à¤ŀ', 'ा', 'पत', 'à¥į', 'रस', 'à¥į', 'य', 'Ġà¤ħन', 'à¥į', 'तर', 'à¥į', 'à¤Ĺततय', 'ा', 'Ġà¤īपलब', 'à¥į', 'ध', 'à¤ĥ', 'Ġà¤ħस', 'à¥į', 'त', 'ि;', 'Ġà¤ħन', 'à¥į', 'य', 'ाà¤ĥ', 'Ġस', 'à¤Ĥ', 'स', 'à¥į', 'थ', 'ि', 'त', 'à¥į', 'य', 'à¤ĥ', 'Ġà¤ħप', 'ि', 'Ġसन', 'à¥į', 'त', 'ि', 'Ġ।', 'Ġà¤ħध', 'ि', 'à¤ķ', 'à¤Ĥ', 'Ġà¤ľ', 'à¥į', 'à¤ŀ', 'ा', 'त', 'à¥ģ', 'म', 'à¥į', 'Ġà¤ħत', 'à¥į', 'र', 'Ġà¤īपय', 'à¥ĭ', 'à¤Ĺस', 'à¥į', 'य', 'Ġस', 'à¤Ĥ', 'स', 'à¥į', 'थ', 'ि', 'त', 'िà¤Ĥ', 'Ġपश', 'à¥į', 'यत', 'à¥ģ', 'Ġ।', 'Ċ', 'à¤ķस', 'à¥į', 'त', 'à¥Ĥ', 'रब', 'ा', 'Ġà¤Ĺ', 'ा', 'न', 'à¥į', 'ध',

In [ ]:
d = tokenizer.decode(ids=x.ids, skip_special_tokens=True)

In [ ]:
print(d)

<s>पाठः क्रियेटिव कॉमन्स ऐट्रिब्यूशन/शेयर-अलाइक अभिज्ञापत्रस्य अन्तर्गततया उपलब्धः अस्ति; अन्याः संस्थित्यः अपि सन्ति । अधिकं ज्ञातुम् अत्र उपयोगस्य संस्थितिं पश्यतु ।
कस्तूरबा गान्धी ( ( शृणु) /ˈkəstuːrəbɑː/) (गुजराती: કસ્તૂરબા ગાંધી, हिन्दी: कस्तूरबा गान्धी, आङ्ग्ल: kasturba gandhi) महात्मनः अर्धम् अङ्गम् । भारतीयस्वतन्त्रतासङ्ग्रामे तस्याः महत् योगदानं वर्तते । स्वास्थ्यस्य विचारमपि अकृत्वा सत्याग्रहान्दोलनाय स्वयोगदानम् अयच्छत् सा । उन्नतपर्वतस्य समीपस्थानि लघुशिखराणि यथा स्वस्य औन्नत्यं सिद्धं कर्तुं न शक्नुवन्ति, तथैव महात्मनः विशालव्यक्तित्वस्य छायायां कस्तूरबा स्वप्रतिभां सिद्धयितुं न शक्तवती । परन्तु उन्नतपर्वतस्य औन्नत्यस्य आधारस्तु समीपस्थानि लघु शिखराणि एव भवन्ति । तथैव महात्मनः विशालव्यक्तित्वस्य एकः आधारः कस्तूरबा अपि आसीत् । सा सुख-दुःखेषु महात्मना सह स्</s>


In [ ]:
import tensorflow as tf
import numpy as np
import os
import io

In [ ]:
# Load Sanskrit text data
data_path = "output.txt"
with io.open(data_path, encoding='utf-8') as f:
    text = f.read().lower()

In [ ]:
len(text[:10000])

10000

In [ ]:
# Custom tokenizer function
def custom_tokenizer(text):
    # Implement your custom tokenizer logic here
    # For example:
    batch_size = 10000
    encoded_tokens = []
    for i in range(0, len(text), batch_size):
        batch_text = text[i:i+batch_size]
        tokens = tokenizer.encode(batch_text).tokens  # Example: Encoding batch of text
        encoded_tokens.extend(tokens)
    return encoded_tokens

In [ ]:
# Tokenize text using your custom tokenizer
tokens = custom_tokenizer(text)

In [ ]:
len(vocab)

16407

In [ ]:
# Create vocabulary
vocab = sorted(set(tokens))
token2idx = {u: i for i, u in enumerate(vocab)}
idx2token = np.array(vocab)

In [ ]:
# Convert text to numerical representation
text_as_int = np.array([token2idx[token] for token in tokens])

In [ ]:
# Define training examples and targets
seq_length = 100  # Length of the sequence for training
examples_per_epoch = len(text_as_int) // seq_length
token_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

sequences = token_dataset.batch(seq_length + 1, drop_remainder=True)

def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [ ]:
# Batch size
BATCH_SIZE = 64

# Buffer size to shuffle the dataset
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

In [ ]:
for i in dataset:
  print(i)
  break

(<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([  444,  4293,  7874,  9825,  8129, 15190, 10724,  5541,  7980,
        5040, 10567,  9709,  7980,  6405, 15190, 10658,  4752, 10724,
        7377, 15123, 10724,  5541,  7980,  4615, 10724,  5040, 10535,
        6939,   115,  6909, 10567,  5299,    66,  8266,  7874,  8432,
       14477,  7980,  9484, 10724,  9673,  7874,  4312, 10724,  5965,
       10724,  5040, 14169, 10724,  3177, 10724,  9037,  7874, 14844,
       10724,  3791,  8129, 14379, 10724,  2988,  8007, 14169, 10724,
        5040,  7930, 13871,  8096,  7377, 10724,  3388,  7980,  2988,
       10724,  5040,  8129, 14205,  7980, 13904, 10724,  2988,  7980,
       15773, 14161,  7980,  8646,  8096, 15546, 10724,  9673,  7874,
        2988, 10469,  4696, 10724, 14137, 10724,  5541, 14833, 10663,
        9200])>, <tf.Tensor: shape=(100,), dtype=int64, numpy=
array([ 4293,  7874,  9825,  8129, 15190, 10724,  5541,  7980,  5040,
       10567,  9709,  7980,  6405, 15190, 10658,  

In [ ]:
# Define the model
vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = tf.keras.Sequential([
        tf.keras.layers.Embedding(vocab_size, embedding_dim,
                                  batch_input_shape=[batch_size, None]),
        tf.keras.layers.LSTM(rnn_units,
                             return_sequences=True,
                             stateful=True,
                             recurrent_initializer='glorot_uniform'),
        tf.keras.layers.Dense(vocab_size)
    ])
    return model

In [ ]:
model = build_model(
    vocab_size=len(vocab),
    embedding_dim=embedding_dim,
    rnn_units=rnn_units,
    batch_size=BATCH_SIZE)

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True))

# Checkpoint to save the model during training
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)


In [ ]:
# Train the model
EPOCHS=10
history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

# Save the model
model.save('sanskrit_language_model.h5')

Epoch 1/10
376/376 [==============================] - 122s 308ms/step - loss: 4.5988
Epoch 2/10
376/376 [==============================] - 108s 282ms/step - loss: 3.8289
Epoch 3/10
376/376 [==============================] - 109s 285ms/step - loss: 3.3302
Epoch 4/10
376/376 [==============================] - 109s 287ms/step - loss: 2.8687
Epoch 5/10
376/376 [==============================] - 103s 270ms/step - loss: 2.6045
Epoch 6/10
376/376 [==============================] - 108s 283ms/step - loss: 2.4283
Epoch 7/10
376/376 [==============================] - 109s 284ms/step - loss: 2.2961
Epoch 8/10
376/376 [==============================] - 108s 284ms/step - loss: 2.1864
Epoch 9/10
376/376 [==============================] - 108s 282ms/step - loss: 2.0917
Epoch 10/10
376/376 [==============================] - 104s 272ms/step - loss: 2.0092


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
import tensorflow as tf
import numpy as np

# Load the saved model
model = tf.keras.models.load_model('sanskrit_language_model.h5')

# Function to generate text
def generate_text(model, start_string, num_generate=1000):
    # Evaluation step (generating text using the learned model)
    input_eval = [token2idx[s] for s in start_string]
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store the generated text
    text_generated = []

    # Low temperatures results in more predictable text.
    # Higher temperatures results in more surprising text.
    temperature = 1.0

    # Here batch size == 1
    model.reset_states()
    for i in range(num_generate):
        predictions = model(input_eval)
        # Remove the batch dimension
        predictions = tf.squeeze(predictions, 0)

        # Using a categorical distribution to predict the character returned by the model
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

        # Pass the predicted character as the next input to the model
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated.append(idx2token[predicted_id])

    return (start_string + ''.join(text_generated))
